cakephpapp-webserver:
  build: .
  dockerfile: docker/nginx/Dockerfile
  container_name: webserver-publications-api
  ports:
    - "80:80"
  links:
    - cakephpapp-php-fpm

cakephpapp-php-fpm:
  build: .
  dockerfile: docker/php-fpm/Dockerfile
  container_name: publications-api
  environment:
    - DEBUG=1
    - DATABASE_URL=mysql://sinc:q6FM8r@fich.unl.edu.ar/sinc

