cakephpapp-webserver:
  image: phpdockerio/nginx:latest
  container_name: webserver-pub-api
  volumes:
    - $PWD/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "8001:80"
  links:
    - cakephpapp-php-fpm

cakephpapp-php-fpm:
  build: .
  dockerfile: docker/php-fpm/Dockerfile
  container_name: publications-api
  environment:
    - DEBUG=1
    - DATABASE_URL=mysql://sinc:q6FM8r@fich.unl.edu.ar/sinc